#!/usr/bin/env node
/**
 * MCP server for @saikarun/s-ai — dependency-free stdio JSON-RPC 2.0.
 *
 * Auto-generated by the TRL/MCP rollout. Implements the Model Context Protocol
 * `tools` capability over stdio. Configuration lives in mcp-server/server_config.json.
 *
 * Run:  node mcp-server/server.mjs
 */
import readline from "node:readline";
import { spawn } from "node:child_process";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.dirname(HERE);
const SERVER_NAME = "@saikarun/s-ai-mcp";
const SERVER_VERSION = "1.0.0";
const PROTOCOL_VERSION = "2024-11-05";
const CLI_TIMEOUT = 180000;

const CONFIG = JSON.parse(readFileSync(path.join(HERE, "server_config.json"), "utf8"));
const APP = CONFIG.app || {};
const ROUTES = CONFIG.routes || [];
const SCRIPTS = CONFIG.scripts || {};
const PAGES = CONFIG.pages || [];
const BASE_URL = process.env.MCP_APP_BASE_URL || CONFIG.base_url || "http://localhost:3000";

const schema = (properties = {}, required = []) => ({
  type: "object",
  properties,
  required,
  additionalProperties: false,
});
const str = (description) => ({ type: "string", description });

function runCommand(cmd, argv) {
  return new Promise((resolve) => {
    const child = spawn(cmd, argv, { cwd: REPO_ROOT, shell: process.platform === "win32" });
    let out = "";
    let err = "";
    const timer = setTimeout(() => child.kill("SIGKILL"), CLI_TIMEOUT);
    child.stdout.on("data", (d) => (out += d));
    child.stderr.on("data", (d) => (err += d));
    child.on("close", (code) => {
      clearTimeout(timer);
      const text = (out + (out && err ? "\n" : "") + err).trim();
      resolve(text || (code === 0 ? "(no output)" : `exit code ${code}`));
    });
    child.on("error", (e) => {
      clearTimeout(timer);
      resolve(`${e.name}: ${e.message}`);
    });
  });
}

async function appInfo() {
  let pkg = {};
  if (existsSync(path.join(REPO_ROOT, "package.json"))) {
    try {
      pkg = JSON.parse(readFileSync(path.join(REPO_ROOT, "package.json"), "utf8"));
    } catch {
      /* ignore */
    }
  }
  return JSON.stringify(
    {
      name: APP.name || pkg.name || SERVER_NAME,
      version: APP.version || pkg.version || "unknown",
      description: APP.description || pkg.description || "",
      repo_root: REPO_ROOT,
      scripts: Object.keys(SCRIPTS),
      routes: ROUTES.map((r) => `${r.method.toUpperCase()} ${r.path}`),
      mcp_server: { name: SERVER_NAME, version: SERVER_VERSION, protocol: PROTOCOL_VERSION },
      tools: Object.keys(TOOLS),
    },
    null,
    2
  );
}

async function routeCall(route, args) {
  let url = BASE_URL.replace(/\/$/, "") + route.path;
  for (const part of route.path.split("/")) {
    if (part.startsWith("{") && part.endsWith("}")) {
      url = url.replace(part, encodeURIComponent(String(args[part.slice(1, -1)] ?? "")));
    }
  }
  if (args.query && typeof args.query === "object") {
    const qs = new URLSearchParams(args.query).toString();
    if (qs) url += (url.includes("?") ? "&" : "?") + qs;
  }
  const method = route.method.toUpperCase();
  const init = { method, headers: { "Content-Type": "application/json" } };
  if (["POST", "PUT", "PATCH"].includes(method) && args.body !== undefined) {
    init.body = JSON.stringify(args.body);
  }
  try {
    const resp = await fetch(url, init);
    const text = await resp.text();
    return resp.ok ? text : `HTTP ${resp.status}: ${text}`;
  } catch (e) {
    return `${e.name}: ${e.message}`;
  }
}

function listPages() {
  return JSON.stringify([...PAGES].sort(), null, 2);
}

function getPage(args) {
  const name = String(args.page ?? "");
  const match = PAGES.find((p) => p === name || p.toLowerCase() === name.toLowerCase());
  if (!match) throw new Error(`unknown page: ${name}`);
  return readFileSync(path.join(REPO_ROOT, match), "utf8");
}

function searchContent(args) {
  const needle = String(args.query ?? "").toLowerCase();
  if (!needle) throw new Error("query is required");
  const hits = [];
  for (const page of PAGES) {
    let text = "";
    try {
      text = readFileSync(path.join(REPO_ROOT, page), "utf8");
    } catch {
      continue;
    }
    text.split("\n").forEach((line, i) => {
      if (line.toLowerCase().includes(needle)) hits.push(`${page}:${i + 1}: ${line.trim().slice(0, 200)}`);
    });
  }
  return hits.slice(0, 200).join("\n") || "(no matches)";
}

function buildTools() {
  const tools = {
    app_info: { description: "Metadata about this application and its MCP server.", inputSchema: schema(), call: appInfo },
  };
  if (Object.keys(SCRIPTS).length) {
    tools.list_scripts = {
      description: "List the npm scripts defined in package.json.",
      inputSchema: schema(),
      call: async () => JSON.stringify(SCRIPTS, null, 2),
    };
    tools.run_script = {
      description: "Run an npm script. `args` is an array of extra string arguments.",
      inputSchema: schema({ name: str("Script name."), args: { type: "array", items: { type: "string" } } }, ["name"]),
      call: async (args) => {
        const name = String(args.name ?? "");
        if (!(name in SCRIPTS)) throw new Error(`unknown script: ${name}`);
        return runCommand("npm", ["run", name, "--", ...(args.args || []).map(String)]);
      },
    };
  }
  for (const route of ROUTES) {
    const safe = `${route.method}_${route.path}`.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "").toLowerCase();
    const params = {};
    const required = [];
    for (const part of route.path.split("/")) {
      if (part.startsWith("{") && part.endsWith("}")) {
        const key = part.slice(1, -1);
        params[key] = str(`Path parameter \`${key}\`.`);
        required.push(key);
      }
    }
    if (["POST", "PUT", "PATCH"].includes(route.method.toUpperCase())) {
      params.body = { type: "object", description: "JSON request body." };
    }
    params.query = { type: "object", description: "Query string parameters." };
    tools[`http_${safe}`] = {
      description: `${route.method.toUpperCase()} ${route.path}`,
      inputSchema: schema(params, required),
      call: (args) => routeCall(route, args),
    };
  }
  if (PAGES.length) {
    tools.list_pages = { description: "List the site's HTML pages.", inputSchema: schema(), call: async () => listPages() };
    tools.get_page = {
      description: "Return a page's HTML source.",
      inputSchema: schema({ page: str("Page path.") }, ["page"]),
      call: async (args) => getPage(args),
    };
    tools.search_content = {
      description: "Search across site pages for a string.",
      inputSchema: schema({ query: str("Text to find.") }, ["query"]),
      call: async (args) => searchContent(args),
    };
  }
  return tools;
}

const TOOLS = buildTools();

async function handle(request) {
  const { method, id } = request;
  if (method === "initialize") {
    return {
      jsonrpc: "2.0",
      id,
      result: {
        protocolVersion: PROTOCOL_VERSION,
        capabilities: { tools: { listChanged: false } },
        serverInfo: { name: SERVER_NAME, version: SERVER_VERSION },
      },
    };
  }
  if (["notifications/initialized", "initialized", "notifications/cancelled"].includes(method)) return null;
  if (method === "ping") return { jsonrpc: "2.0", id, result: {} };
  if (method === "tools/list") {
    return {
      jsonrpc: "2.0",
      id,
      result: {
        tools: Object.entries(TOOLS).map(([name, t]) => ({
          name,
          description: t.description,
          inputSchema: t.inputSchema,
        })),
      },
    };
  }
  if (method === "tools/call") {
    const params = request.params || {};
    const spec = TOOLS[params.name];
    if (!spec) {
      return { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: `Unknown tool: ${params.name}` }], isError: true } };
    }
    try {
      const text = await spec.call(params.arguments || {});
      return { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: String(text) }], isError: false } };
    } catch (e) {
      return { jsonrpc: "2.0", id, result: { content: [{ type: "text", text: `${e.name}: ${e.message}` }], isError: true } };
    }
  }
  if (method === "resources/list") return { jsonrpc: "2.0", id, result: { resources: [] } };
  if (method === "prompts/list") return { jsonrpc: "2.0", id, result: { prompts: [] } };
  if (id === undefined || id === null) return null;
  return { jsonrpc: "2.0", id, error: { code: -32601, message: `Method not found: ${method}` } };
}

const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: false });
rl.on("line", async (line) => {
  const trimmed = line.trim();
  if (!trimmed) return;
  let request;
  try {
    request = JSON.parse(trimmed);
  } catch (e) {
    process.stdout.write(JSON.stringify({ jsonrpc: "2.0", id: null, error: { code: -32700, message: String(e) } }) + "\n");
    return;
  }
  const response = await handle(request);
  if (response) process.stdout.write(JSON.stringify(response) + "\n");
});
